import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faBackspace,
  faDivide,
  faEquals,
  faMinus,
  faPercentage,
  faPlus,
  faSquareRootAlt,
  faTimes,
} from '@fortawesome/free-solid-svg-icons';

export const keyboardLayoutOptions = {
  ios: [
    { value: 'clear', label: 'AC', type: 'extraOption' },
    { value: 'backspace', label: <FontAwesomeIcon icon={faBackspace} />, type: 'extraOption' },
    { value: '%', label: <FontAwesomeIcon icon={faPercentage} />, type: 'extraOption' },
    { value: '/', label: <FontAwesomeIcon icon={faDivide} />, type: 'operator' },
    { value: '7', label: 7 },
    { value: '8', label: 8 },
    { value: '9', label: 9 },
    { value: '*', label: <FontAwesomeIcon icon={faTimes} />, type: 'operator' },
    { value: '4', label: 4 },
    { value: '5', label: 5 },
    { value: '6', label: 6 },
    { value: '-', label: <FontAwesomeIcon icon={faMinus} />, type: 'operator' },
    { value: '1', label: 1 },
    { value: '2', label: 2 },
    { value: '3', label: 3 },
    { value: '+', label: <FontAwesomeIcon icon={faPlus} />, type: 'operator' },
    { value: '0', label: 0, extended: 'right' },
    { value: '.', label: '.' },
    { value: 'solve', label: <FontAwesomeIcon icon={faEquals} />, type: 'solve' },
  ],
  android: [
    { value: 'clear', label: 'C', type: 'operator' },
    { value: '/', label: <FontAwesomeIcon icon={faDivide} />, type: 'operator' },
    { value: '*', label: <FontAwesomeIcon icon={faTimes} />, type: 'operator' },
    { value: 'backspace', label: <FontAwesomeIcon icon={faBackspace} />, type: 'operator' },
    { value: '7', label: 7 },
    { value: '8', label: 8 },
    { value: '9', label: 9 },
    { value: '-', label: <FontAwesomeIcon icon={faMinus} />, type: 'operator' },
    { value: '4', label: 4 },
    { value: '5', label: 5 },
    { value: '6', label: 6 },
    { value: '+', label: <FontAwesomeIcon icon={faPlus} />, type: 'operator' },
    { value: '1', label: 1 },
    { value: '2', label: 2 },
    { value: '3', label: 3 },
    { value: 'solve', label: <FontAwesomeIcon icon={faEquals} />, type: 'solve', extended: 'bottom' },
    { value: '%', label: <FontAwesomeIcon icon={faPercentage} /> },
    { value: '0', label: 0 },
    { value: '.', label: '.' },
  ],
  windows: [
    { value: 'clear', label: 'CE', type: 'operator' },
    { value: 'backspace', label: <FontAwesomeIcon icon={faBackspace} />, type: 'operator' },
    { value: 'square-root', label: <FontAwesomeIcon icon={faSquareRootAlt} />, type: 'operator' },
    { value: '/', label: <FontAwesomeIcon icon={faDivide} />, type: 'operator' },
    { value: '7', label: 7 },
    { value: '8', label: 8 },
    { value: '9', label: 9 },
    { value: '*', label: <FontAwesomeIcon icon={faTimes} />, type: 'operator' },
    { value: '4', label: 4 },
    { value: '5', label: 5 },
    { value: '6', label: 6 },
    { value: '-', label: <FontAwesomeIcon icon={faMinus} />, type: 'operator' },
    { value: '1', label: 1 },
    { value: '2', label: 2 },
    { value: '3', label: 3 },
    { value: '+', label: <FontAwesomeIcon icon={faPlus} />, type: 'operator' },
    { value: '%', label: <FontAwesomeIcon icon={faPercentage} /> },
    { value: '0', label: 0 },
    { value: '.', label: '.' },
    { value: 'solve', label: <FontAwesomeIcon icon={faEquals} />, type: 'solve' },
  ],
};
